[package]
name = "tvs-libs"
version = "0.1.0"
edition = "2021"

[dependencies]
tvs-libs-macros = { path = "macros" }
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"
serde_bytes = "0.11"
bytemuck = { version = "1.13", features = ["derive"] }
js-sys = "0.3"
lerp = "0.5"
approx = "0.5.1"
rand = "0.8.5"
getrandom = { version = "0.2", features = ["js"] }
glam = { version = "0.24.0", features = [
	"bytemuck",
	"serde",
	"rand",
	"approx",
] }
