[package]
name = "tvs-libs"
version = "0.1.0"
edition = "2021"

[dependencies]
tvs-libs-macros = { path = "macros" }
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"
serde_bytes = "0.11"
bytemuck = { version = "1.13", features = ["derive"] }
glam = { version = "0.24", features = ["bytemuck", "serde"] }
js-sys = "0.3"
lerp = "0.5"
