[package]
name = "draft_triangle"
edition.workspace = true

[dependencies]
trivalibs.workspace = true
shader = { path = "./shader", package = "draft_triangle_shader" }
png.workspace = true
bytemuck.workspace = true
